Fix: Back to search results button functionality
openmrs/openmrs-esm-patient-management pull request #1044
Opened 2024-03-16 08:05 UTC by sam-sny

## Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [ ] My work includes tests or is validated by existing tests.

## Summary

## Screenshots

## Related Issue

## Other

2024-03-17 00:00 UTC, mseaton requested changes
@sam-sny seem my comments.  Also, can you please create a branch for your changes rather than issuing changes directly from main?

2024-03-21 21:25 UTC, mseaton requested changes
Not sure what you are presenting here @sam-sny , but I don't think it's intended for this issue.

2024-03-22 05:25 UTC, Vijaykv5 commented on package.json
> +    "react-joyride": "^2.8.0",
Why are you adding a third party library for fixing this issue? @sam-sny

2024-05-28 17:28 UTC, denniskigen commented
Closing as stale

2024-05-28 17:28 UTC, closed without merging