(BREAKGING) O3-2748 service queues - add ability to undo transitions and void queue entries
openmrs/openmrs-esm-patient-management pull request #1052
Opened 2024-03-19 21:21 UTC by chibongho

## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [x] My work includes tests or is validated by existing tests.

## Summary

This PR adds additions actions on queue entries to be able to void them or undo transitions in case the entry is created / transitioned by mistake.

This PR is dependent on cooresponding change to the backend. [PR](https://github.com/openmrs/openmrs-module-queue/pull/64) here.

## Screenshots

![image](https://github.com/openmrs/openmrs-esm-patient-management/assets/509602/5ca492de-2543-4d85-944b-26948d1f819b)
![image](https://github.com/openmrs/openmrs-esm-patient-management/assets/509602/d0a9a72a-695e-430f-9e73-fc844bd4130e)
![image](https://github.com/openmrs/openmrs-esm-patient-management/assets/509602/35530456-d48a-4cd5-910b-0141f58ba388)

## Related Issue

## Other

2024-03-20 19:05 UTC, ojwanganto commented
This is a good addition @chibongho. I am wondering if this can be extended to take care of queuing back to the previous location i.e. from lab to clinical room. Do you have such use-cases in your workflows?

2024-03-20 19:06 UTC, ojwanganto approved these changes
LGTM

2024-03-20 20:36 UTC, chibongho commented
> This is a good addition @chibongho. I am wondering if this can be extended to take care of queuing back to the previous location i.e. from lab to clinical room. Do you have such use-cases in your workflows?

@ojwanganto with the current implementation, undoing a transition will only queue the patient back to wherever their previous queue entry was. If their most recent transition was from a different location, it would do what you described. Otherwise, the user will have to do "undo transition" multiple times until the system re-activates a queue entry from a previous location. 

In our use case, we only have one queue per location, so the distinction between queue and location is not important to us. Do you have a use case for undo multiple transitions at once?

2024-03-20 20:46 UTC, denniskigen approved these changes
Nice work, @chibongho! I've left a couple of nitpicky suggestions.

2024-03-20 20:46 UTC, denniskigen commented on packages/esm-service-queues-app/src/queue-table/cells/queue-table-action-cell.component.tsx
> +          aria-label="Actions"
Nit: this should be translated

2024-03-20 20:46 UTC, denniskigen commented on packages/esm-service-queues-app/src/queue-table/cells/queue-table-action-cell.component.tsx
> +          aria-label="Actions"
Same here

2024-03-20 20:46 UTC, denniskigen commented on packages/esm-service-queues-app/src/queue-table/queue-entry-actions/queue-entry-actions-modal.component.tsx
>  // Modal with form to provide the same UI for editting or transitioning a queue entry
```suggestion
// Modal with a form to provide the same UI for editing or transitioning a queue entry
```

2024-03-21 12:11 UTC, CynthiaKamau approved these changes

2024-03-22 12:28 UTC, mseaton requested changes
Overall looks great @chibongho , nice work!  See my comments for some changes requested, nothing major.

2024-03-22 12:28 UTC, mseaton commented on packages/esm-service-queues-app/src/queue-table/cells/queue-table-action-cell.component.tsx
> +          {t('void', 'Void')}
"Void" isn't really an end-user facing term that we tend to use.  Typically, we'd present this as this "Delete".  Voiding is a technical detail as to how we perform deletes on the back end.

2024-03-22 12:28 UTC, mseaton commented on packages/esm-service-queues-app/src/queue-table/cells/queue-table-action-cell.component.tsx
> +          {t('moveBack', 'Move back')}
This isn't really correct.  "Move back" to me, implies that the original transition was correct, and now they are done there and need to go back in the other queue again.  This is really here as an _alternative_ to "Delete", which is essentially "Delete and reactivate previous queue entry" or "Undo this transition".  We need to make it explicit that this is here to _revert_ the previous action, as if it had never happened.

2024-03-22 12:28 UTC, mseaton commented on packages/esm-service-queues-app/src/queue-table/queue-entry-actions/queue-entry-undo-actions-modal.component.tsx
> +          subtitle: error?.message,
Ideally you'd work with your back end changes to ensure whatever message is coming from the back end that indicates a failure state (eg. no previous queue entry, multiple matching previous queue entries, etc) could be passed here via a localized message.  i.e. can we create an appropriate Exception class that, when it propogates through to here, we have access to both a message code and a default message that we can use to present the error.

2024-03-22 12:28 UTC, mseaton commented on packages/esm-service-queues-app/src/queue-table/queue-entry-actions/void-queue-entry-modal.component.tsx
> +  const modalInstruction = <p>{t('confirmVoidQueueEntry', 'Are you sure you want to void this queue entry?')}</p>;
void -> delete

2024-03-22 12:28 UTC, mseaton commented on packages/esm-service-queues-app/src/queue-table/queue-entry-actions/void-queue-entry-modal.component.tsx
> +        submitAction: (queueEntry) => voidQueueEntry(queueEntry.uuid),
Void -> Delete above where appropriate.

2024-03-22 16:00 UTC, mseaton approved these changes
LGTM - thanks!

2024-03-22 16:40 UTC, sam-sny commented
Good One

2024-03-22 18:26 UTC, merged