O3-999: Added outpatient app side panel search bar
openmrs/openmrs-esm-patient-management pull request #107
Opened 2022-02-14 10:42 UTC by CynthiaKamau

## Requirements

- [x] This PR has a title that briefly describes the work done, on ticket O3-999.
- [x] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [x] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary

## Screenshots
<img width="969" alt="PatientSearch" src="https://user-images.githubusercontent.com/19533785/153848503-2306214d-d0ea-45c3-a842-1ef17d743a77.PNG">
<img width="958" alt="AdvancedSearch" src="https://user-images.githubusercontent.com/19533785/153848521-7366d87b-1173-442d-8190-ade45b709e50.PNG">

## Issue

https://issues.openmrs.org/projects/O3/issues/O3-999

## Screenshots

*None.*

## Related Issue

*None.*

## Other

*None.*

2022-02-14 18:26 UTC, brandones commented
@CynthiaKamau Please do not open new PRs for the same change. Doing that gets rid of the history of your work and our conversation about it. This makes it much harder for whoever is reviewing (in this case, me) to keep track of things.

I tried to close this one and re-open the previous one and it says that the entire repository that had the previous change had been deleted. I don't know why you would do that. There is no reason you should ever have to do that.

You can edit your PR title and description in GitHub directly. You can push updates to your code as new commits to the same branch. It looks like you are using the `main` branch of your fork for everything. I would recommend using branches for different issues. Please [learn how to use git](http://o3-dev.docs.openmrs.org/#/getting_started/prerequisites?id=git) before attempting to contribute.

2022-02-16 11:39 UTC, CynthiaKamau commented
> @CynthiaKamau Please do not open new PRs for the same change. Doing that gets rid of the history of your work and our conversation about it. This makes it much harder for whoever is reviewing (in this case, me) to keep track of things.
> 
> I tried to close this one and re-open the previous one and it says that the entire repository that had the previous change had been deleted. I don't know why you would do that. There is no reason you should ever have to do that.
> 
> You can edit your PR title and description in GitHub directly. You can push updates to your code as new commits to the same branch. It looks like you are using the `main` branch of your fork for everything. I would recommend using branches for different issues. Please [learn how to use git](http://o3-dev.docs.openmrs.org/#/getting_started/prerequisites?id=git) before attempting to contribute.

I will have to close this pr and open another one with my new branch

2022-02-16 16:05 UTC, brandones commented
No, I promise, you do not have to do that. Please learn to use git. Merge your changes into this branch and push it.

2022-02-21 06:21 UTC, donaldkibet requested changes
@CynthiaKamau please fix the conflicts, few suggestion in general LGTM 🍻

2022-02-21 06:21 UTC, donaldkibet commented on packages/esm-outpatient-app/src/patient-search/patient-search.component.tsx
> +import PatientAdvancedSearchLaunch from './patient-advanced-search.component';
```suggestion
import PatientAdvancedSearch from './patient-advanced-search.component';
```

2022-02-21 06:21 UTC, donaldkibet commented on packages/esm-outpatient-app/src/patient-search/patient-search.component.tsx
> +  const handleSearchMode = (searchMode: SearchMode) => {
```suggestion
  const toggleSearchMode = (searchMode: SearchMode) => {
```

2022-02-21 06:21 UTC, donaldkibet commented on packages/esm-outpatient-app/src/patient-search/patient-simple-search.component.tsx
> +  handleAdvanceSearch: (searchMode: SearchMode) => void;
```suggestion
  toggleSearchMode: (searchMode: SearchMode) => void;
```

2022-02-21 11:35 UTC, merged