(fix):Fix queue number not being displayed
openmrs/openmrs-esm-patient-management pull request #1117
Opened 2024-04-30 12:09 UTC by makombe

## Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [ ] My work includes tests or is validated by existing tests.

## Summary

## Screenshots

## Related Issue

## Other

2024-04-30 12:22 UTC, mseaton approved these changes

2024-04-30 13:15 UTC, donaldkibet requested changes
Thanks @makombe to prevent regression please add a unit test for this.

2024-04-30 13:53 UTC, chibongho commented
Looks good. thanks!

2024-06-05 09:47 UTC, jwnasambu commented
@makombe Kindly you have merge conflicts to be addressed.

2024-06-05 22:15 UTC, donaldkibet approved these changes

2024-06-05 22:15 UTC, merged