(refactor) O3-3806: Refactor Service queue entries api call using OpenMrs Fetch All
openmrs/openmrs-esm-patient-management pull request #1394
Opened 2024-12-02 19:01 UTC by kb019

## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [x] My work includes tests or is validated by existing tests.

## Summary
To use hooks already present in esm-core to fetch all the queue entries.

[388370799-867ef32b-fb36-4a01-a49b-c5fbf7d3b0ff.webm](https://github.com/user-attachments/assets/69cac106-ddb8-4053-a2fa-fc4bf86f6eaa)

## Related Issue
https://openmrs.atlassian.net/browse/O3-3806

## Other

2024-12-19 03:52 UTC, brandones requested changes
It's a great idea but your implementation doesn't make any sense (yet).

2024-12-19 03:52 UTC, brandones commented on packages/esm-service-queues-app/src/patient-queue-metrics/clinic-metrics.component.tsx
> +  const { data } = useSWR<QueueEntryResponse>(
You are no longer using `useQueueEntries` at all. I can't imagine that this works in cases where the number of entries exceeds the page size. I did my development and testing of this feature by creating 11 service queue entries and setting the page size to 3. I recommend you do something similar. There are a lot of edge cases that we need to make sure will continue to work.

2024-12-19 03:52 UTC, brandones commented on packages/esm-service-queues-app/src/hooks/useQueueEntries.ts
> +    if (initialMount) {
First off, this `initialMount` is a ref, so it is always true. You want `initialMount.current`.

But moreover, if `pageUrl` changes, then `useOpenmrsFetchAll` will get called with the new value of `pageUrl` as a parameter. Why would you call `mutate` at the same time?

2025-01-03 16:22 UTC, brandones commented on packages/esm-service-queues-app/src/patient-queue-metrics/clinic-metrics.component.tsx
> +  const { data } = useSWR<QueueEntryResponse>(
@kb019 wrote me on Slack with the following explanation:

> Before this pr , useQueueEntries was used in two places , one to show metrics and other one in the queue Table.  The useSwrInfinite used in useOpenmrsFetchAll Hook does not seem to cache results and leads to calling the url twice for each pageIndex. So i thought that inorder to show metrics we dont need to wait until all results are fetched.We can just get the metadata from the first url and show that.So i am not using useQueueEntries in clinic metrics component and just relying on useSWR.

Which makes sense!

2025-01-03 16:27 UTC, brandones requested changes
Great work @kb019 , just one suggestion for further simplification

2025-01-03 16:27 UTC, brandones commented on packages/esm-service-queues-app/src/hooks/useQueueEntries.ts
> + const queueUpdateListener = useCallback(() => {
I think we simplify this further. I think we can get rid of all the `queueUpdateListener` and `queue-entry-updated` stuff, and whatever function it is that triggers the `queue-entry-updated` event. We can simply expose the mutate function and use that.

2025-01-10 14:57 UTC, brandones requested changes

2025-01-10 14:57 UTC, brandones commented on packages/esm-service-queues-app/src/hooks/useQueueEntries.ts
> +let queueEntryMutates: ReturnType<typeof useQueueEntries>['mutate'][] = [];
Do we still need `useMutateQueueEntries` at all, or can we just have `useQueueEntries` return the `mutate` returned by `useOpenmrsFetchAll`?

2026-03-11 06:39 UTC, jayasanka-sack commented
This PR has been inactive for quite some time and the codebase has changed significantly since it was opened.

We’re marking it as graveyard-candidate and may close it soon as part of repository cleanup.

If you're still interested in continuing the work, please let us know and we'd be happy to help revive it.

2026-06-16 09:15 UTC, jayasanka-sack commented
We're going to close this PR due to inactivity and as part of our repository cleanup. Thanks for the contribution. If you'd like to pick this up again in the future, feel free to reopen or create a new PR. Happy to help. 🙌

2026-06-16 09:15 UTC, closed without merging