O3-999 - added scheduled visits list
openmrs/openmrs-esm-patient-management pull request #145
Opened 2022-03-30 18:19 UTC by CynthiaKamau

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary

After searching for a patient, when a user clicks on any of the patients in the outpatient app, another workspace should appear to allow them to view the patients scheduled visits.

## Screenshots
![Screenshot (35)](https://user-images.githubusercontent.com/19533785/160128819-efac70a8-6930-4cb5-8b86-4ccbc44d530b.png)

## Related Issue

*None.*

## Other

*None.*

2022-03-31 06:37 UTC, CynthiaKamau commented
Kindly review : @donaldkibet @denniskigen

2022-04-05 08:06 UTC, donaldkibet requested changes

2022-04-05 08:06 UTC, donaldkibet commented on packages/esm-outpatient-app/src/patient-search/patient-scheduled-visits.component.tsx
> +  const [show_recent_priority, setShowRecentPriority] = useState(false);
the project uses camelCase should stick to that for consistency

2022-04-05 08:06 UTC, donaldkibet commented on packages/esm-outpatient-app/src/patient-search/patient-search.component.tsx
> +          ) : searchType === SearchTypes.SCHEDULED_VISITS ? (
SCHEDULE_VISIT is not a search type I would extract the logic for displaying scheduled visits away from search type to something like `showScheduleVisit`

2022-04-08 09:32 UTC, donaldkibet approved these changes

2022-04-08 09:33 UTC, merged