added medications in previous visits tab in outpatient app
openmrs/openmrs-esm-patient-management pull request #220
Opened 2022-05-25 13:44 UTC by CynthiaKamau

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary
<img width="959" alt="pastVisitMedications" src="https://user-images.githubusercontent.com/19533785/170276618-5258c207-491f-4dfc-8990-82180fdda8fe.PNG">

## Screenshots

*None.*

## Related Issue

*None.*

## Other

*None.*

2022-05-25 14:22 UTC, CynthiaKamau commented
Kindly review : @makombe @donaldkibet @denniskigen

2022-05-25 14:39 UTC, makombe requested changes

2022-05-25 14:41 UTC, makombe commented
Generally looks good.

2022-05-26 09:19 UTC, makombe approved these changes

2022-05-26 09:20 UTC, merged