O3-1268: Default Identifiers types should not be required
openmrs/openmrs-esm-patient-management pull request #240
Opened 2022-06-09 06:01 UTC by vasharma05

## Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [x] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [x] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary

Default patient identifier types should not be required to be filled when registering a patient.

## Screenshots

*None.*

## Related Issue

https://issues.openmrs.org/browse/O3-1268").

## Other

*None.*

2022-06-09 08:43 UTC, ZacButko requested changes
Logic looks ok. Please restore translations if they are still in use.

2022-06-10 02:37 UTC, vasharma05 commented on packages/esm-outpatient-app/translations/en.json
> -  "futureScheduledVisits": " {count, plural, one{{count} visit} other{{count} visits}} scheduled for dates in the future",
This translation is removed from the outpatient app.

2022-06-10 02:38 UTC, vasharma05 commented on packages/esm-patient-registration-app/translations/en.json
> -  "birthdayRequired": "Birthdate is required",
These translations removal will not occur again after #242 is merged, meanwhile restoring the translations back

2022-06-16 19:15 UTC, ZacButko commented
OBE by PR https://github.com/openmrs/openmrs-esm-patient-management/pull/243

2022-06-16 19:15 UTC, closed without merging