MF-687: Extend desktop search overlay to cover left navigation
openmrs/openmrs-esm-patient-management pull request #39
Opened 2021-08-14 11:14 UTC by donaldkibet

### Description

1. Extended desktop search to cover the left navigation
2. Updated the search experience to match the designs as shown [here](https://app.zeplin.io/project/60d59321e8100b0324762e05/dashboard?tag=Patient%20search)

## Screenshoots

### Desktop Search Experience
![desktop](https://user-images.githubusercontent.com/28008754/129444461-595fab82-4b56-4f8a-91e7-ac313920c48c.gif)

### Tablet search experience
![tablet](https://user-images.githubusercontent.com/28008754/129444485-5e3dc57b-5c31-4cfb-a1f5-765bc1004e1f.gif)

2021-08-14 23:37 UTC, FlorianRappl requested changes

2021-08-14 23:37 UTC, FlorianRappl commented on packages/esm-patient-search-app/src/patient-search-icon/patient-search-icon.component.tsx
> +import { Button } from 'carbon-components-react';
Use submodule import.

2021-08-14 23:37 UTC, FlorianRappl commented on packages/esm-patient-search-app/src/patient-search-icon/patient-search-icon.component.tsx
> +    return () => ac.abort();
Why is a function returned here? Do you intend to use this in a side-effect hook? Right now its not.

2021-08-14 23:37 UTC, FlorianRappl commented on packages/esm-patient-search-app/src/patient-search-icon/patient-search-icon.component.tsx
> +  const performSearch = () => {
The whole callback here screams for being used inside a side effect hook.

In the current state

- cancellation will never work
- if the component is unmounted during the resource loading we get state errors left and right

2021-08-16 12:22 UTC, FlorianRappl approved these changes
LGTM!

2021-08-16 12:22 UTC, merged

2021-08-16 23:51 UTC, gracepotma commented
THANK YOU FOR THIS ONE DONALD! Very nice to have this done. It was bugging me 😅