(test) O3-1885: Implement edit patient e2e test
openmrs/openmrs-esm-patient-management pull request #553
Opened 2023-02-19 07:54 UTC by RandilaP

## Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [x] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [x] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary
This pull request adds an end-to-end test for editing patient details. The test covers the following scenarios:

- Editing the patient's first name
- Editing the patient's middle name
- Editing the patient's last name
- Editing the patient's gender
- Editing the patient's date of birth
- Editing the patient's address
- Editing the patient's phone number

## Screenshots

*None.*

## Related Issue
https://issues.openmrs.org/browse/O3-1885

## Other

*None.*

2023-02-19 07:54 UTC, RandilaP commented
@jayasanka-sack Could you please review this PR

2023-02-19 08:15 UTC, jayasanka-sack requested changes
Thanks @RandilaP ! I added some comments. Let me know if you require further clarification. :)

2023-02-19 08:15 UTC, jayasanka-sack commented on e2e/pages/registrationAndEditPage.ts
> +
Remove this unused variable

2023-02-19 08:15 UTC, jayasanka-sack commented on e2e/pages/registrationAndEditPage.ts
> +export class registrationAndEditPage {
```suggestion
export class RegistrationAndEditPage {
```

2023-02-27 03:41 UTC, anjula-sack approved these changes
Good job! @RandilaP LGTM

2023-02-27 06:56 UTC, jayasanka-sack approved these changes
Thanks @RandilaP !

2023-02-27 06:56 UTC, merged