(fix) O3-1930: Add timeout in edit patient e2e test
openmrs/openmrs-esm-patient-management pull request #569
Opened 2023-02-27 16:59 UTC by RandilaP

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary
- Added a timeout in edit patient e2e test because that test was flaky

## Screenshots

*None.*

## Related Issue
https://issues.openmrs.org/browse/O3-1930

## Other

*None.*

2023-02-27 16:59 UTC, RandilaP commented
@jayasanka-sack Could you please review this

2023-02-28 05:59 UTC, jayasanka-sack requested changes

2023-02-28 05:59 UTC, jayasanka-sack commented on e2e/specs/patientEdit.spec.ts
> +  await expect(patientEditPage.givenNameInput()).not.toHaveValue('', { timeout: 1000000 });
I think 2 mins would be enough for this.

2023-02-28 06:21 UTC, jayasanka-sack approved these changes
Thanks for getting this done, @RandilaP!

2023-02-28 06:22 UTC, merged