The "Edit patient list" form doesn't load the list type automatically
openmrs/openmrs-esm-patient-management pull request #605
Opened 2023-03-16 18:55 UTC by chirandevinda

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary
The edit-patient-list form doesn't load the patient list type (cohortType) automatically. The current patient list type should be the default value on the drop-down menu.
This problem occurs because our endpoint doesn't automatically get the cohortType in the payload. We are currently using a custom representation, so the cohortType field should be added to the list of the required fields.

## Screenshots
![image](https://user-images.githubusercontent.com/73557402/225721152-f310d5e0-bd30-45ed-b5ad-d55984fc00ab.png)

![image](https://user-images.githubusercontent.com/73557402/225724232-b0158b36-e8bc-43a8-9517-e5b12795e71e.png)

## Related Issue

*None.*

## Other

*None.*

2023-03-17 06:05 UTC, anjula-sack approved these changes
Thank you! @chirandevinda

2023-03-17 18:02 UTC, Jexsie requested changes
Thanks, @chirandevinda, did you test this and confirm it is working? I think there is more to do.

2023-03-17 19:39 UTC, Jexsie commented
Also, check back on jira for updates on this issue

2023-03-17 21:21 UTC, Piumal1999 reviewed
Good job @chirandevinda 

Could you please include the JIRA ticket link in the "Related Issue" section on the pull request template? Also, the PR title should contain the ticket number and a title briefly describing the work done. Example: `(fix) O3-1965: Load the current cohortType on edit patient list form`

2023-03-18 11:20 UTC, Jexsie commented
Hey @Piumal1999 and @chirandevinda. Discussing this with @hadijahkyampeire, she told me that the drop-down will be removed. Users will only be allowed to create lists of type **My list**. But I also think the cohortType might still be needed. Good work @chirandevinda

2023-03-18 13:09 UTC, Jexsie approved these changes

2023-03-18 14:03 UTC, ibacher approved these changes

2023-03-21 07:46 UTC, merged