(test) O3-2218 O3-2219: Add test for `add-patient-link` and `nav-link tests` components
openmrs/openmrs-esm-patient-management pull request #749
Opened 2023-07-02 19:44 UTC by ayush-AI

## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary

In this PR I have added tests for add-patient-link and nav-link components.

## Screenshots

*None.*

## Related Issue

https://issues.openmrs.org/browse/O3-2218
https://issues.openmrs.org/browse/O3-2219

## Other

*None.*

2023-07-02 19:45 UTC, ayush-AI commented
cc @jayasanka-sack @anjula-sack @Piumal1999

2023-07-03 04:06 UTC, anjula-sack requested changes

2023-07-03 04:06 UTC, anjula-sack commented on packages/esm-patient-registration-app/src/add-patient-link.test.tsx
> +describe('Root component', () => {
```suggestion
describe('Add patient button', () => {
```

2023-07-03 04:06 UTC, anjula-sack commented on packages/esm-patient-registration-app/src/nav-link.test.tsx
> +describe('Root component', () => {
```suggestion
describe('Nav link component', () => {
```

2023-07-03 18:22 UTC, anjula-sack approved these changes
Good job! @ayush-AI

2023-07-03 18:23 UTC, merged