(test) O3-2297: Add tests for `visit-detail.component.tsx`
openmrs/openmrs-esm-patient-management pull request #771
Opened 2023-07-31 16:22 UTC by ayush-AI

## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary

In this PR I have added tests for `visit-detail.component.tsx`

## Screenshots

*None.*

## Related Issue

[O3-2297](https://issues.openmrs.org/browse/O3-2297)

## Other

*None.*

2023-07-31 16:37 UTC, ayush-AI commented
cc/ @Piumal1999 @anjula-sack @jayasanka-sack

2023-08-03 18:27 UTC, Piumal1999 requested changes

2023-08-03 18:27 UTC, Piumal1999 commented on packages/esm-active-visits-app/src/visits-summary/visit-detail.test.tsx
> +  const patientUuid = 'some-patient-uuid';
For these kinds of variables, let's use `uuid`s similar to actual `uuid`s. (I think there's a specific format and the number of characters in openmrs uuids)

2023-08-03 18:27 UTC, Piumal1999 commented on packages/esm-active-visits-app/src/visits-summary/visit-detail.test.tsx
> +    });
We can mock it like this:

```
useVisit.mockReturnValue({
      visit: null,
      isLoading: true,
});
```

2023-08-03 18:27 UTC, Piumal1999 commented on packages/esm-active-visits-app/src/visits-summary/visit-detail.test.tsx
> +    screen.debug();
Can you elaborate on the usage of this line?

2023-08-03 18:27 UTC, Piumal1999 commented on packages/esm-active-visits-app/src/visits-summary/visit-detail.test.tsx
> +    });
Let's do the same to other `mockReturnValue` function calls as well

2023-08-08 13:34 UTC, ayush-AI commented
@Piumal1999 I updated the PR please have a look.

2023-08-10 12:23 UTC, Piumal1999 approved these changes
Thank you @ayush-AI

2023-08-10 12:38 UTC, merged

2023-08-10 13:48 UTC, jayasanka-sack commented
@Piumal1999 @ayush-AI Tests have been failing since this PR. Could you please fix it as soon as possible?