(fix) O3-1925: Patient list starring by user fixed
openmrs/openmrs-esm-patient-management pull request #775
Opened 2023-08-09 08:26 UTC by vasharma05

## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [x] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).
- [x] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary
This PR includes the facility to star a patient list by the user. The starred patient list's UUID is stored in the `userProperties` object in the user data on the backend and is considered the source of truth for the same.

## Screenshots

https://github.com/openmrs/openmrs-esm-patient-management/assets/51502471/644e667a-e2a2-4ec7-a652-1f2cb2cbd858

## Related Issue
https://issues.openmrs.org/browse/O3-1925

## Other

*None.*

2023-08-23 12:48 UTC, vasharma05 commented
Hi @ibacher @denniskigen @hadijahkyampeire , please review the PR.
Thanks!

2023-08-23 13:47 UTC, ibacher requested changes
Thanks Vineet a few things that could use some small adjustments.

2023-08-23 13:47 UTC, ibacher commented on packages/esm-patient-list-app/src/api/hooks.ts
> +export function useCurrentUser() {
User properties are returned as part of the session, so this hook seems redundant...

2023-08-23 13:47 UTC, ibacher commented on packages/esm-patient-list-app/src/patient-list-list/patient-list-table.component.tsx
> +          description: 'Marking patient lists starred/ unstarred failed',
It would be great if this was translatable.

```suggestion
          description: 'Marking patient lists starred / unstarred failed',
```

2023-08-23 13:47 UTC, ibacher commented on packages/esm-patient-list-app/src/patient-list-list/patient-list-table.component.tsx
> +  const toggleStarredList = (cohortUuid, starPatientList) => {
Probably best to wrap this in a `useCallback()`

2023-09-24 21:18 UTC, denniskigen commented
Could you finish the requested changes, @vasharma05?

2023-09-28 12:46 UTC, vasharma05 commented
Yes @denniskigen , I'll be on it.
Thanks!

2023-11-02 09:46 UTC, denniskigen commented
@vasharma05 are you unblocked by Brandon's changes in core?

2023-12-28 10:51 UTC, brandones commented
Yes, the changes in core unblocked this. I've gotten this PR cleaned up and merged with the latest, including https://github.com/openmrs/openmrs-esm-patient-management/pull/865 which it had some collision with. Will merge once everything is green.

2023-12-28 11:50 UTC, merged

2023-12-28 11:53 UTC, brandones commented
Thanks for your work on this @vasharma05 !