(test): Add tests for `compact-patient-search.component.tsx`
openmrs/openmrs-esm-patient-management pull request #785
Opened 2023-08-14 22:28 UTC by ayush-AI

## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary

In this PR, I have added tests for `compact-patient-search.component.tsx`

## Screenshots

*None.*

## Related Issue

*None.*

## Other

*None.*

2023-08-14 22:29 UTC, ayush-AI commented
cc/ @Piumal1999 @anjula-sack @jayasanka-sack

2023-08-15 07:13 UTC, anjula-sack requested changes

2023-08-15 07:13 UTC, anjula-sack commented on packages/esm-patient-search-app/src/compact-patient-search/compact-patient-search.test.tsx
> +    // expect(selectPatientActionMock).toHaveBeenCalled();
```suggestion
```

2023-08-23 13:42 UTC, anjula-sack approved these changes
Thank you! @ayush-AI

2023-08-23 13:42 UTC, merged

2024-02-10 23:24 UTC, brandones commented
@ayush-AI @anjula-sack These tests verify absolutely nothing. A test that verifies that text entered into an input appears in the input is worthless (unless you have built the input from scratch). Creating fake tests like this is extremely counter-productive; it adds friction to getting actual work done, without doing anything to ensure that things don't get broken, which is the entire point of tests.

Please don't do things like this; please get your changes reviewed by someone qualified to review them. Approving things like this constitutes performance way below expectations for /dev/3.

2024-02-10 23:42 UTC, brandones commented on packages/esm-patient-search-app/src/compact-patient-search/compact-patient-search.test.tsx
> +  });
These tests verify absolutely nothing. Please do not write tests like this, @ayush-AI . @anjula-sack please do not approve tests like this.

2024-02-11 00:03 UTC, brandones commented on packages/esm-patient-search-app/src/compact-patient-search/compact-patient-search.test.tsx
> +  });
And then these two tests obviously don't test that anything different happens whether there is user input or not. Absolutely useless.

2024-02-14 03:53 UTC, gracepotma commented
Brandon friendly reminder to please be respectful in comments. 
However I'm concerned about the technical takeaway here. @jayasanka-sack can you have a look at this - do we need to remove this code if it's adding clutter, or better yet, update it to offer the originally intended coverage?

2024-02-14 03:56 UTC, brandones commented on packages/esm-patient-search-app/src/compact-patient-search/compact-patient-search.test.tsx
> +  });
Sorry for the tone guys, this was out of line.