(test) Add tests for `add-patient-to-patient-list-menu-item.component.tsx`
openmrs/openmrs-esm-patient-management pull request #787
Opened 2023-08-17 21:00 UTC by ayush-AI

## Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary

In this PR I have added the tests for `add-patient-to-patient-list-menu-item.component.tsx`

## Screenshots

*None.*

## Related Issue

*None.*

## Other

*None.*

2023-08-17 21:01 UTC, ayush-AI commented
cc/ @Piumal1999 @jayasanka-sack @anjula-sack

2023-08-18 12:49 UTC, Piumal1999 requested changes

2023-08-18 12:49 UTC, Piumal1999 commented on packages/esm-patient-list-app/src/add-patient-to-patient-list-menu-item.test.tsx
> +    render(<AddPatientToPatientListMenuItem patientUuid="someUuid" />);
Use a sample uuid

2023-08-18 12:49 UTC, Piumal1999 commented on packages/esm-patient-list-app/src/add-patient-to-patient-list-menu-item.test.tsx
> +    render(<AddPatientToPatientListMenuItem patientUuid="someUuid" />);
Same here

2023-08-23 12:14 UTC, ayush-AI commented on packages/esm-patient-list-app/src/add-patient-to-patient-list-menu-item.test.tsx
> +    render(<AddPatientToPatientListMenuItem patientUuid="someUuid" />);
Done @Piumal1999

2023-08-23 13:44 UTC, anjula-sack approved these changes

2023-08-23 13:44 UTC, merged