(feat) add support to search relationship by patient identifier on registration form
openmrs/openmrs-esm-patient-management pull request #851
Opened 2023-10-17 07:49 UTC by Herobiam

## Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary

Enhancing the registration form's relationship creation feature has been addressed in this pull request (PR). Formerly, the search functionality was limited to first and last names, omitting the option to search using the patient identifier. The proposed changes in this PR extend the search capabilities to encompass patient identifiers, thereby providing a more comprehensive and efficient method for establishing relationships within the registration process.

## Screenshots

https://github.com/openmrs/openmrs-esm-patient-management/assets/19629227/6da3f20b-3830-4793-8246-5e3869eb6940

## Related Issue

*None.*

## Other

*None.*

2023-10-18 07:25 UTC, pirupius commented on packages/esm-patient-registration-app/src/patient-registration/patient-registration.resource.tsx
> +      : `${BASE_API}/patient?q=${query}`;
This looks like something that could be optimized. 2 api calls will end up being made to `/person` with the second one being made  on line 194

2023-10-25 09:55 UTC, eudson requested changes

2023-10-25 09:55 UTC, eudson commented on packages/esm-patient-registration-app/src/patient-registration/patient-registration.resource.tsx
> +    console.error('Error fetching person:', error);
@Herobiam can you remove this console log please

2023-10-25 14:41 UTC, ibacher commented
I’m closing this in favour of #856, which implements the same logic.

2023-10-25 14:41 UTC, closed without merging

2023-10-25 15:13 UTC, Herobiam commented
Okay great thanks @ibacher