(feat) 03 2572 Implement the new snack bar in patient management(part 1)
openmrs/openmrs-esm-patient-management pull request #888
Opened 2023-11-29 19:57 UTC by NYESIGA

Use the new snackbar in all places where Toast and Notification were used in patient management in first 3 apps of patient management that is active-visit-app,appointment-app and patient-list-management-app   

 Screenshots

![Screenshot (95)](https://github.com/openmrs/openmrs-esm-patient-management/assets/110772072/7ad7b264-64ca-4788-9260-a25f41c29f80)

https://openmrs.atlassian.net/browse/O3-2572

2023-11-29 23:03 UTC, hadijahkyampeire requested changes
Thanks @NYESIGA just a few improvements, mainly about the isLowContrast prop, just a note; All success snackbars should have a true lowcontrast prop and error snackbars should have false but I think if you don't pass the prop it will default to false, just ensure to test error snackbars and confirm that they all have a high contrast i.e black background.

2023-11-29 23:03 UTC, hadijahkyampeire commented on packages/esm-patient-list-management-app/src/list-details-table/list-details-table.component.tsx
> +        isLowContrast: false,
```suggestion
        isLowContrast: false,
        isLowContrast: true
```

2023-11-30 20:04 UTC, NYESIGA reviewed
@hadijahkyampeire  i have made changes as you suggested

2023-11-30 20:55 UTC, hadijahkyampeire requested changes
Still a few success snackbars missing isLowContrast, please ensure all success snackbars must have `isLowContrast: true`

2023-11-30 20:55 UTC, hadijahkyampeire commented on packages/esm-patient-list-management-app/src/add-patient/add-patient.component.tsx
> +          showSnackbar({
@NYESIGA I still don't see isLowContrast

2023-11-30 20:55 UTC, hadijahkyampeire commented on packages/esm-patient-list-management-app/src/create-edit-patient-list/create-edit-list.component.tsx
> +          showSnackbar({
@NYESIGA you missed this too

2023-11-30 20:55 UTC, hadijahkyampeire commented on packages/esm-patient-list-management-app/src/list-details/list-details.component.tsx
> +        showSnackbar({
Also this @NYESIGA

2023-12-01 16:20 UTC, NYESIGA reviewed
i have removed   this console.error('Error updating list: ', error); on line 62

2023-12-01 16:52 UTC, NYESIGA reviewed
@hadijahkyampeire is there any change i need to make

2023-12-04 23:30 UTC, hadijahkyampeire commented
@NYESIGA let me know if you wanna pair on the lint issue.

2023-12-06 16:40 UTC, njiddasalifu requested changes
@NYESIGA I think you are getting the fail due to many commits. Can you squash them into one commit and try again.

2024-01-05 19:24 UTC, hadijahkyampeire commented
@NYESIGA I am gonna close this since I can push to it and open a new one.

2024-01-05 19:24 UTC, closed without merging